name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/Retkon.SuperScoped.sln

    - name: Build Solution
      run: dotnet build src/Retkon.SuperScoped.sln --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Generate NuGet package
      if: ${{ success() }}
      run: dotnet pack src/Retkon.SuperScoped.sln -c Release --output ${{ env.NuGetDirectory }}
      
    - name: Publish NuGet package
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      run: |
        foreach ($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
